<?php

return array (
  'name' => '开化新时代文明实践智能云管理系统',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'system' => '系统配置',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'video' => '点播配置',
    'live' => '直播配置',
    'data' => '数据配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'check_switch' => '2',
  'publish_switch' => '1',
  'is_auto_img' => '1',
  'is_server' => '1',
  'appid' => '10001',
  'wxappid' => '',
  'wxappsecret' => '',
  'no_publish' => '1',
  'is_event_order' => '1',
  'lbs_weather_key' => '969be7016fc5b9f0d8313a402bc0fc9d',
  'sms_id' => '208208',
  'cst_live_url' => 'http://59.63.205.84:10000/interface/interface.php?',
  'cst_live_public_url' => 'http://wypc.cst-info.cn:8090',
  'cst_live_private_url' => 'http://10.60.46.7:9001',
  'cst_video_url' => 'http://10.27.161.26:10086/',
  'cst_video_public_url' => 'http://220.191.236.254:8004/',
  'cst_video_private_url' => 'http://220.191.236.254:8004/',
  'tvvisit' => '22222',
  'wxvisit' => '1000',
  'pcvisit' => '1000',
  'center' => '1',
  'place' => '1',
  'station' => '11',
  'spot' => '111',
  'volunteer' => '11111',
  'volunteergroup' => '11111',
  'activity' => '123',
  'activityjoin' => '12333',
  'activitytime' => '0',
  'totalfield' => '12',
  'availablefield' => '12',
  'buildingfield' => '12',
  'horse' => '开化新时代文明实践上线啦！！',
);